# You can manually run the Dependabot update by going to Myy repository in Github
# Insights -> Dependency Graph -> Dependabot -> Check for updates

version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Helsinki"
    #  From docs:
    #  Always increase the minimum version requirement to match the new version.
    #  If a range already exists, typically this only increases the lower bound.
    versioning-strategy: increase
    groups:
      eslint:
        patterns:
          - "eslint*"