name: CI checks

on:
  pull_request:
permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Approve and Merge PR
        if: github.actor == 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash approve_and_merge.sh $GITHUB_TOKEN ${{ github.repository_owner }} ${{ github.repository }} ${{ github.event.pull_request.number }}