name: Dependabot auto-approve and merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  approve-and-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for checks to pass
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          all_checks_pass=false
          start_time=$(date +%s)
          while [ "$all_checks_pass" != "true" ]; do
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))
            if [ $elapsed_time -ge 180 ]; then
              echo "Timeout reached. Exiting..."
              exit 1
            fi

            status=$(gh pr checks "$pr_number" --json | jq '.[].state' | grep -v '"success"')
            if [ -z "$status" ]; then
              all_checks_pass=true
            else
              echo "Waiting for all checks to pass..."
              sleep 10  # Adjust the interval between checks as needed
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --merge "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
